# Model configuration for GeneFix AI
model:
  type: MutationDetectionModel
  input_channels: 4
  conv_out_channels: 32
  conv_kernel_size: 3
  lstm_hidden_size: 64
  num_classes: 2
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
